In [42]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer

In [49]:
def most_similar(sentences, embeddings, query_embedding, k = 5):
    X = np.stack(embeddings)
    score_map = zip(sentences, cosine_similarity(X, query_embedding.reshape(1, -1)))
    return sorted(score_map, key=lambda v: v[1], reverse=True)[:k]

In [4]:
corpus_path = '../masterthesis/data/scidtb.csv'

corpus = pd.read_csv(corpus_path, sep='\t', header=None)

sentences = corpus[2]

In [5]:
model = SentenceTransformer('bert-base-nli-mean-tokens')

100%|███████████████████████████████████████████████████████████████████████████████| 405M/405M [06:03<00:00, 1.11MB/s]


In [8]:
sentence_embeddings = model.encode(sentences)

In [15]:
query = "Efficient software packages are rarely employed in practice for tuning NLP models because their interoperability with deep learning frameworks such as PyTorch is not optimized."

query_embedding = model.encode([query])[0]

In [51]:
most_similar(sentences, sentence_embeddings, query_embedding, 3)

[('These systems suffer from poor portability across domains and their benefit for NLP tasks that involve sentence-level processing is limited.',
  array([0.8247389], dtype=float32)),
 ('The informal nature of social media text renders it very difficult to be automatically processed by natural language processing tools.',
  array([0.8205497], dtype=float32)),
 ('This leads to far fewer language model calls, but while LR decoding is more efficient than CKY decoding, it is unable to capture some hierarchical phrase alignments reachable using CKY decoding and suffers from lower translation quality as a result.',
  array([0.80016696], dtype=float32))]